name: Weekly simulation amd64 build

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch: {}

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Free disk space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Clone external repos
        run: CLONE_ONLY=true ./scripts/sim_build.sh 

      - name: Build the simulation image
        run: docker build -t simulation-image -f ./scripts/docker/Dockerfile.simulation .
