name: aircraft-image arm64

on:
  schedule:
    - cron: '0 3 * * 6'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    timeout-minutes: 120
    permissions:
      contents: read
      packages: write

    steps:       
      - name: Add swap space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Check swap
        run: |
          free -h
          sudo swapon --show

      - name: Check disk space
        run: df -h

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Clone external repos
        run: CLONE_ONLY=true ./scripts/deploy_build.sh

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the aircraft image
        run: docker buildx build -t aircraft-image -f ./scripts/docker/Dockerfile.aircraft .
