name: Weekly aircraft arm64 build

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    timeout-minutes: 120

    steps:       
      - name: Add swap space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Check swap
        run: |
          free -h
          sudo swapon --show

      - name: Check disk space
        run: df -h

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Clone external repos and build the image
        run: ./scripts/deploy_build.sh 
